[package]
name = "ssg-test"
version = "0.1.0"
edition = "2021"

[dependencies]
grass = "0.13.1"
# ibex = { path = "../ibex" }
ibex = { git = "https://github.com/darccyy/ibex" }
serde = { version = "1.0.189", features = ["derive"] }
